### ISSUE TITLE
是否有相关文档？

### ISSUE THREAD

**Issue by seamusic** [Secyud/Abp#1]
代码库包括了不少内容，不知道有没有替换的文档可以研究一下？

**Comment by laoxTu** [comment]
> 代码库包括了不少内容，不知道有没有替换的文档可以研究一下？

实现的文档没有写。
不过官方有一些使用其它Blazor组件的文档，这篇文章[MudBlazor Theme in ABP Blazor WebAssembly PART 1](https://community.abp.io/posts/mudblazor-theme-in-abp-blazor-webassembly-ae23zz17)可能会有用。

**Comment by mimimiaomiao1** [comment]
> > 代码库包括了不少内容，不知道有没有替换的文档可以研究一下？
> 
> 实现的文档没有写。 不过官方有一些使用其它Blazor组件的文档，这篇文章[MudBlazor Theme in ABP Blazor WebAssembly PART 1](https://community.abp.io/posts/mudblazor-theme-in-abp-blazor-webassembly-ae23zz17)可能会有用。

你好,请问用户,角色,租户这些都有吗?

**Comment by laoxTu** [comment]
> > > 代码库包括了不少内容，不知道有没有替换的文档可以研究一下？
> > 
> > 
> > 实现的文档没有写。 不过官方有一些使用其它Blazor组件的文档，这篇文章[MudBlazor Theme in ABP Blazor WebAssembly PART 1](https://community.abp.io/posts/mudblazor-theme-in-abp-blazor-webassembly-ae23zz17)可能会有用。
> 
> 你好,请问用户,角色,租户这些都有吗?

我复刻了租户管理的blazor代码，但是角色和用户的并没有，需要引用主题，然后用MasaBlazor的组件重写一个。
而后端只需要引用ABP原来的Application以及Domain或者扩展它们即可。
当然我现在并没有聚焦在这个项目上，所以这个项目可能会随着时间变得老旧。

**Comment by mimimiaomiao1** [comment]
> 

Please blend in
